# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "backlog_items", :force => true do |t|
    t.column "title",                   :string
    t.column "estimate",                :integer
    t.column "position",                :integer
    t.column "type",                    :string
    t.column "project_id",              :integer
    t.column "product_backlog_item_id", :integer
  end

  create_table "projects", :force => true do |t|
    t.column "title",     :string
    t.column "position",  :integer
    t.column "sprint_id", :integer
  end

  create_table "sprints", :force => true do |t|
    t.column "number",   :integer
    t.column "start_on", :date
    t.column "end_on",   :date
  end

end
